### ISSUE TITLE
new bereal update

### ISSUE THREAD

**Issue by 083noah** [chemokita13/BeRealGate#19]
could you update it, that it work again? would be great!

**Comment by chemokita13** [comment]
Im a student in a exams week, I will be working on it, but at least for sundey I won't start

**Comment by jjj120** [comment]
I tried getting informations on where the new api endpoints are, here is what I found, but I think it is not super useful information because I could not decrypt the https and TLS traffic. 
- https request to auth.bereal.team (probably new authentication method, since it is https I could not find out anything more)
- https requests to the following to download images:
- - cdn-cf.bereal.network
- - cdn-goo.bereal.com
- - cdn.bereal.network
- TLS connection to ogma.bereal.team (this looks like something with certificates, but I have no clue what for, since it is sent after the last cdn call)

I got this information by using PCAPdroid on my phone, but installing the certificate of PCAPdroid to decrypt the requests is not working, because the connections from bereal just fail then. 

Just wanted to share the infos I found out, but i haven't found anything useful to further reverse engineer the api

**Comment by chemokita13** [comment]
@jjj120  Solved! Thanks for the info
